### ISSUE TITLE
[REBUILD] Hell Revealed 2 needs testing!!!

### ISSUE THREAD

**Issue by mifu666** [Mythotic-Tinker-Station/lexicon#74] opened 2020-04-28 12:50 UTC
Hell Revealed 2 was just re-added to the rebuild branch. This requires testing from the crack team of mapset testers.

Please add a note to the ticket if you are testing this and please report back on the following:

Any texture issues (missing or incorrect textures etc)

- Thing issues (incorrect decorations. monsters etc
- Show stopping bugs
- Any other issues

This should be tested within the week before the weekend with the other mapsets added.

**Comment by michael-is-qcde** [comment] 2020-04-28 14:40
HR207 initial view, should be a normal Doom switch on a wall similar to other walls
![image](https://user-images.githubusercontent.com/57696110/80500745-c1f03280-8998-11ea-9b33-2f7d4a5e0ed1.png)

**Comment by michael-is-qcde** [comment] 2020-04-28 16:59
This floor on HR223 seems to be lit with glow, like lava. It shouldn't be
![image](https://user-images.githubusercontent.com/57696110/80515379-118c2980-89ac-11ea-9c96-f451a5e52e4d.png)

**Comment by michael-is-qcde** [comment] 2020-04-28 17:51
HR228 exit teleporter is misaligned and wrong. It should be a normal white teleporter from Doom.
![image](https://user-images.githubusercontent.com/57696110/80520229-57002500-89b3-11ea-92e7-fad2a124cca2.png)

**Comment by michael-is-qcde** [comment] 2020-04-29 08:34
HR2_04: This wall traps the player who entered the red door. For coop, it should be possible to open from outside.
![image](https://user-images.githubusercontent.com/57696110/80576122-d8e16400-8a2e-11ea-8652-09cc9b17f6e5.png)

**Comment by michael-is-qcde** [comment] 2020-04-29 08:38
HR2_06: This door near start only opens once. For coop, it should be repeatable.
![image](https://user-images.githubusercontent.com/57696110/80576434-5f964100-8a2f-11ea-8507-4d78ba7d47a6.png)

**Comment by michael-is-qcde** [comment] 2020-04-29 09:08
HR2_12: These 4 Arachnotrons consistently fail to spawn in.
![image](https://user-images.githubusercontent.com/57696110/80579020-92dacf00-8a33-11ea-8270-4ba45f3fcb54.png)

**Comment by michael-is-qcde** [comment] 2020-04-29 10:17
HR2_31: Cannot cross this necessary bridge. Appear to be blocked when going over. Going under works fine.
The other bridge nearby also blocks but crossing is possible with some wiggle.
![image](https://user-images.githubusercontent.com/57696110/80585096-f0274e00-8a3c-11ea-88eb-c8912916bc02.png)
![image](https://user-images.githubusercontent.com/57696110/80585113-fae1e300-8a3c-11ea-8e46-63442a301af4.png)

**Comment by michael-is-qcde** [comment] 2020-04-29 10:47
HR2_16: This switch opening blue skull bars only works once. For coop, as well as preventing softlock in single player, it should be repeatable.
![image](https://user-images.githubusercontent.com/57696110/80587481-d4be4200-8a40-11ea-8773-97b3958905c3.png)

**Comment by michael-is-qcde** [comment] 2020-04-29 10:47
HR2_16: This switch doesn't change appearance when pressed.
![image](https://user-images.githubusercontent.com/57696110/80587848-7cd40b00-8a41-11ea-8800-a734652d0d32.png)

**Comment by michael-is-qcde** [comment] 2020-04-29 11:14
HR2_19: Can't cross this necessary bridge, something's blocking me.
![image](https://user-images.githubusercontent.com/57696110/80589858-25379e80-8a45-11ea-8142-bda8fbf7c166.png)
![image](https://user-images.githubusercontent.com/57696110/80589932-45fff400-8a45-11ea-8fa6-1738cf5e67e0.png)

**Comment by michael-is-qcde** [comment] 2020-04-29 11:52
HR2_24: Another impassable bridge. This one, unlike the others, never lowers. This bridge always remains at the same height, player never passes under it.
![image](https://user-images.githubusercontent.com/57696110/80592864-59fa2480-8a4a-11ea-98c8-55834bcd5a0b.png)
![image](https://user-images.githubusercontent.com/57696110/80592961-87df6900-8a4a-11ea-8748-c7a7f3889143.png)

**Comment by michael-is-qcde** [comment] 2020-04-29 11:59
HR2_24: Similarly impassable bridge section. This one would normally activate monster closets when player crosses it. This may or may not be related to its corruption.
![image](https://user-images.githubusercontent.com/57696110/80593413-63d05780-8a4b-11ea-846e-3226d609262d.png)

**Comment by michael-is-qcde** [comment] 2020-05-07 15:03
Most of the issues discovered so far were resolved.

Remaining issues:

HR2_12: These 4 Arachnotrons consistently fail to spawn in.
![image](https://user-images.githubusercontent.com/57696110/80579020-92dacf00-8a33-11ea-8270-4ba45f3fcb54.png)

_Dev note: Fixed in commit 5e3214b_

HR2_16: This switch opening blue skull bars only works once. For coop, as well as preventing softlock in single player, it should be repeatable.
![image](https://user-images.githubusercontent.com/57696110/80587481-d4be4200-8a40-11ea-8773-97b3958905c3.png)

_Dev note: Fixed in commit 484c3d8_

**Comment by Tribeam** [comment] 2020-05-07 15:34
Fixed Arachnotrons not teleporting into the map in commit 5e3214b

Changed one time switch to a repeatable in commit 484c3d8

**Comment by michael-is-qcde** [comment] 2020-05-07 16:02
Confirmed these two issues as fixed!

**Comment by michael-is-qcde** [comment] 2020-05-07 17:40
HR2_29: Wrong floor texture in the Hell's Cauldron (final section)
![image](https://user-images.githubusercontent.com/57696110/81326689-60307680-90c4-11ea-9534-53cee78edb3f.png)

Should be:
![image](https://user-images.githubusercontent.com/57696110/81326715-66265780-90c4-11ea-9a81-3ae7c621d91c.png)

_Dev note: Fixed in commit 8c8d151_

**Comment by michael-is-qcde** [comment] 2020-05-07 18:07
HR2_30: Wrong floor texture on the pentagrams (map start and 4 more in the same area)
![image](https://user-images.githubusercontent.com/57696110/81328850-c79bf580-90c7-11ea-94ce-4d043e1009cc.png)

Supposed to be:
![image](https://user-images.githubusercontent.com/57696110/81329095-3711e500-90c8-11ea-9b99-1e5fc46c3e71.png)

_Dev note: Fixed in commit 8c8d151_

**Comment by Tribeam** [comment] 2020-05-07 22:57
Fixed HR2_29 and HR2_30 texture issues in commit 8c8d151

**Comment by michael-is-qcde** [comment] 2020-05-08 06:18
Confirming texture issues as fixed.

**Closed as completed** 2020-05-10 02:23 UTC
