### ISSUE TITLE
[REBUILD] Hadephobia needs testing!!!

### ISSUE THREAD

**Issue by mifu666** [Mythotic-Tinker-Station/lexicon#83] opened 2020-05-12 01:54 UTC
Hadephobia was just re-added to the rebuild branch. This requires testing from the crack team of mapset testers.

Please add a note to the ticket if you are testing this and please report back on the following:

    Any texture issues (missing or incorrect textures etc)
    Thing issues (incorrect decorations, monsters etc)
    Show stopping bugs
    Any other issues

This should be tested within the week before other mapsets are added.

_Please note that the HUB map is currently being rebuilt and is not available right now, use_ `changemap HADE01` _to start the mapset_

Also note this mapset has known missing textures. Let us know if these are actually in the map

**Comment by Fluffx** [comment] 2020-05-14 17:21
Log shows missing textures on HADE09, but couldn't find them on the map

![Screenshot_38](https://user-images.githubusercontent.com/26505960/81965269-18f03b80-9618-11ea-800e-e6d762410c33.png)

_Dev note: Fixed in commit feb8d16_

**Comment by Tribeam** [comment] 2020-05-14 17:37
These missing textures are original wad issues, we're unsure if they are visible during normal play, and are debating if we should just null them out.

**Comment by Fluffx** [comment] 2020-05-14 17:47
Same deal with Hade10

![Screenshot_39](https://user-images.githubusercontent.com/26505960/81967810-c6b11980-961b-11ea-90c8-10c140ddd2fc.png)

_Dev note: Fixed in commit feb8d16_

**Comment by Tribeam** [comment] 2020-05-14 17:57
Fixed HADE09 and 10 missing textures in commit feb8d16

**Comment by Fluffx** [comment] 2020-05-14 22:06
Missing textures:

### HADE31
![Screenshot_40](https://user-images.githubusercontent.com/26505960/81990242-0fc69500-963f-11ea-82c5-0ba31625ff49.png)

### HADE16
![Screenshot_42](https://user-images.githubusercontent.com/26505960/81990358-4ac8c880-963f-11ea-932e-22d5da9193e2.png)

### HADE17
![Screenshot_43](https://user-images.githubusercontent.com/26505960/81990374-54523080-963f-11ea-9241-674a520192e1.png)

### HADE18
![Screenshot_44](https://user-images.githubusercontent.com/26505960/81990392-6502a680-963f-11ea-8c5a-7901d45eaa3e.png)

### HADE19
![Screenshot_45](https://user-images.githubusercontent.com/26505960/81990414-6f24a500-963f-11ea-8a68-7f77dcfb2281.png)

### HADE22
![Screenshot_47](https://user-images.githubusercontent.com/26505960/81990488-8cf20a00-963f-11ea-9308-91dc12a50d0e.png)

### HADE30
![Screenshot_40s](https://user-images.githubusercontent.com/26505960/81990515-9b402600-963f-11ea-91ce-47c59875789f.png)

_Dev Note: All texture issues fixed in commit 33691e6_

**Comment by Fluffx** [comment] 2020-05-14 22:09
Some maps have issues with commander keens:

### HADE32:
![Screenshot_41](https://user-images.githubusercontent.com/26505960/81990796-26b9b700-9640-11ea-8219-ca928c6238a4.png)

![Screenshot_Doom_20200514_205216](https://user-images.githubusercontent.com/26505960/81990825-3507d300-9640-11ea-8272-3c4f8d03896c.png)

### HADE20
![Screenshot_46](https://user-images.githubusercontent.com/26505960/81990848-418c2b80-9640-11ea-8935-a5d339c0123b.png)

![Screenshot_Doom_20200514_215943](https://user-images.githubusercontent.com/26505960/81990854-45b84900-9640-11ea-9994-661413d691e8.png)

_Dev note: Fixed in commit 717da78_

**Comment by Fluffx** [comment] 2020-05-14 22:09
HADE25, 33, 34 and 35 are not playing their music tracks

**Comment by Tribeam** [comment] 2020-05-15 06:44
All texture issues fixed in commit 33691e6

**Comment by Tribeam** [comment] 2020-05-15 07:38
The music issues are all original wad issues, heres a break down of why:

HADE25's song seems to be corrupt or something, nothing can play it.

HADE33, 34, and 35 do not have tracks because doom2 only goes up to 32, I would consider this as intended by the author.

**Comment by Tribeam** [comment] 2020-05-15 07:45
A friend has fixed the corrupt hade25 song file from the original wad, 
Fixed in commit 3a81106

**Comment by Tribeam** [comment] 2020-05-15 07:57
Fixed Keen actor having wrong sprite names in commit 717da78

**Closed as completed** 2020-05-15 16:04 UTC
